spring:

  main.banner-mode: off

  jooq:
    sql-dialect: Postgres

  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"

